site_name: PyKronecker

nav:
    - Overview: index.md
    - User Guide:
        - Installation: install.md
        - Getting Started:
              - Basic operators: getting_started/operators.md
              - Deriving new operators: getting_started/composite.md
              - Block operators: getting_started/block.md
              - Automatic Differentiation: getting_started/autodiff.md
              - Other features: getting_started/features.md
        - GPU Support and JAX: jax.md
        - API Reference:
              - KroneckerOperator: api/kroneckeroperator.md
              - KroneckerProduct: api/kroneckerproduct.md
              - KroneckerSum: api/kroneckersum.md
              - KroneckerDiag: api/kroneckerdiag.md
              - KroneckerIdentity: api/kroneckeridentity.md
              - KroneckerBlock: api/kroneckerblock.md
              - KroneckerBlockDiag: api/kroneckerblockdiag.md
        - Maths: maths.md
#        - Developers: about.md

theme: readthedocs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math